language: python
python:
- 2.7
- 3.6
env:
- NOPLUGINS=true
install:
- pip install -r requirements-tests.txt
- python setup.py install
script: pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: melund
  password:
    secure: i4d6JbdKHbN8Ww4po6EByRPnRxRYe3Z41jaIqc/RDChKu8MTaQGAOZ8FppwHWYK0QsRL7kGGv4KPDs70uqqDktwwvrrqfNhT6z885EzXkI8OYDRRTEFU7Hz25GIC9sDnW9bN88doE/H/4ezPKAy6HSNWNbCsDIEVePc5B6506VsFpBO6juCRhFBA+00o9kr4VyqWlA2g9IzsV8qQr8R6CPeggvqlr2m4rZk3a6aLaj0/zKSORqyDdvmfnOPvgDVxB4qHr+FXOamqoR9BzMHu2iGFIdQN4tteb2T3iH0i4FTQLiJuAD7JNGfxc8F3sC5M2SMFRjZveB6FnKoqroJQgfSPRpFGA7SIh2FleL4zKaeG74VYOCLkwt0Ls/RI0YdKKhIdwOeXqYj947GhCXnCqyTdkthHL+BNn79SqK8oVf5QhB46TmTFPPAGaA5rDEtx/fCnVk0BgxgVkwF+UFlscVg4VpydNfXlvwgLxU4xFhObDXe7iZJTC26j4kJ3s3ltCNZATqXE6hXSeHB86BgtZTVVwLqFGxD45L1MiePwVyJ+o373Sox4bmj8NYd40/Y7AVAVrSoqmN1XSZQBHIONmMnX2mLF+1itH2tPdwIZMGvagaEGW/wP2YRxRULQbsV4HkZ0qrmHOTzhLnNCk07/WydkAFcIHn7rhEAboDVRZCE=
  on:
    tags: true
    repo: AnyBody/pygments-anyscript
    python: 3.6
