language: python
python:
- 2.7
- 3.6
env:
- NOPLUGINS=true
install:
- pip install -r requirements-tests.txt
- python setup.py install
script: pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: melund
  password:
    secure: axSYYOl3lelGWy1kCUAcwe32BvUnbpViQc1JFP4hTNeY1hoUUckdMJu83Fj+ThmwM20AsZmsLVo6fiwEYDxdBEbqlGrjSTTbUONx9oq/ThdP7i4tPQhWOm8r7VfcXUNYNSNwiZg/YPnp9U+xA9vAgQOP3lhsP6srQJ3IN0dk5hfK+UiojP3stDJLgBEj3ssLQghF812UZr5LSmMB69zDMh3k7SOVcxRE08Sl9O9M988Pv+QfsLIcIu9aO88Q8sJBl7xhYfE9O35Ah19guwcqLOjdHl5Lno1PYRAAHAoo9UxA+/DU68XcHSHGRTtLsJFFR7B38DZMH8IHICNiwGh1CZckFA63tBjnqFrc9AAFnKVxd1m6NA9AF+qSPCW8arZm3emXp4ZUW87SoPmPzEfz8ta/c+bM9TNmzdq4MD/uZWpKi+wl7VNA1p38Z6Uz+ev8oMrl2JOMFNXhowUBzlhHmbaXjwXXObQumfYA7UzAzvl8HGnyJAMDP1LAqj6vxif/d9zV9DdNzrzFUvW2+Nchlwwitt841wrzUCvrAjnF5DFAG2NMeLVkedkArC7k5dlkrCQejMwLgahbR+XGdcvVmRgALOd/C0t8p9PxoSjGMESESS7uiAr4Bf4g2d2NNeqSWpfQ0OhNWkrpRiNRwilZXjHacJOL7u/1lxWUINPy+vM=
  on:
    tags: true
    repo: AnyBody/pygments-anyscript
    python: 3.6
