# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7
  - 3.5
  - 3.6


env:
  - NOPLUGINS=true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements-tests.txt
    - python setup.py install


# command to run tests, e.g. python setup.py test
script: pytest --flake8



# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
#deploy:
#    # Test pypi
#  - provider: pypi
#    distributions: sdist
#    server: https://testpypi.python.org/pypi
#    user: melund
#    password:
#      secure: PLEASE_REPLACE_ME
#    on:
#      tags: false
#      repo: anybody/pygments_anyscript
#      condition: $TRAVIS_PYTHON_VERSION = "3.6"
#    # Production pypi
#  - provider: pypi
#    distributions: sdist bdist_wheel
#    user: melund
#    password:
#      secure: PLEASE_REPLACE_ME
#    on:
#      tags: true
#      repo: anybody/pygments_anyscript
#      condition: $TRAVIS_PYTHON_VERSION = "3.6"

